---
title: "CD4Tcell_extraction_Azimuth"
author: "Daiki Takeuchi, Yoshiaki Yasumizu"
date: "2022/04/23"
output: html_notebook
df_print: paged
source data: https://covid19.cog.sanger.ac.uk/submissions/release1/haniffa21.processed.h5ad
---

# Ensure

```{r Ensure, eval=FALSE, include=FALSE}
# Ensure Seurat v4.0 or higher is installed
if (packageVersion(pkg = "Seurat") < package_version(x = "4.0.0")) {
  stop("Mapping datasets requires Seurat v4 or higher.", call. = FALSE)
}

# Ensure glmGamPoi is installed
if (!requireNamespace("glmGamPoi", quietly = TRUE)) {
  if (!requireNamespace("BiocManager", quietly = TRUE)) {
    BiocManager::install("glmGamPoi")
  }
}

# Ensure Azimuth is installed
if (packageVersion(pkg = "Azimuth") < package_version(x = "0.3.1")) {
  stop("Please install azimuth - remotes::install_github('satijalab/azimuth')", call. = FALSE)
}
```

# 1. Library

```{r library}
library(Seurat)
library(SeuratData)
library(SeuratDisk)
library(Azimuth)
library(patchwork)
library(tidyverse)
library(sctransform)

source('../functions.R')
```

# 2. Parameter setting

```{r parameter setting}
progect.name <- "E-MTAB-10026"
```

# 3. Load the reference

```{r Load_the_reference}
reference <- LoadReference(path = "https://seurat.nygenome.org/azimuth/references/v1.0.0/human_pbmc")
```

# 4. Convert h5ad and LoadH5Seurat(query object)

```{r reading data}
Convert("../../data/E-MTAB-10026/haniffa21.processed.h5ad", dest = "h5seurat", overwrite = TRUE)
query <- LoadH5Seurat("../../data/E-MTAB-10026/haniffa21.processed.h5seurat")

query <- subset(query, subset = Status %in% c("Covid", "Healthy"))
query@meta.data$Status <- factor(as.character(query@meta.data$Status))
levels(query@meta.data$Status) <- list(Covid  = "Covid", HC = "Healthy")
query$sample_id <- factor(query$sample_id)
levels(query@meta.data$Age_interval) <- c(25, 35, 45, 55, 65, 75, 85, 95)
query@meta.data$Age_interval <- query@meta.data$Age_interval %>% as.character() %>% as.numeric()
query@meta.data <- query@meta.data %>% 
  mutate(sample = patient_id,
         disease = Status,
         disease_duration = NA,
         condition = Status_on_day_collection_summary,
         age = Age_interval,
         sex = Sex,
         immunosuppressant = NA,
         immunosuppressant_duration = NA,
         batch = patient_id)
query@meta.data['project'] <- progect.name
query@meta.data['Cell'] <- rownames(query@meta.data)

query@meta.data <- query@meta.data %>%
  relocate(Cell,
           sample,
           disease,
           disease_duration,
           condition,
           age,
           sex,
           immunosuppressant,
           immunosuppressant_duration,
           batch)
```

# 5. process

```{r process}
for (sample in levels(query@meta.data$sample_id)) {
  print(sample)
  prefix = paste0("../../output/", progect.name, "/", sample)
  
  q <- subset(query, subset = sample_id == as.character(sample))
  q <- CreateSeuratObject(counts = q[["raw"]],
                            project = progect.name,
                            assay = "RNA",
                            meta.data = q@meta.data,
                            min.cells = 3,
                            min.features = 200) 
  
  extract_cells(q, reference, prefix)
}
```

# 6. Save workspace

```{r save.image}
prefix = paste0("../../output/", progect.name, "/")
save.image(file = paste0(prefix, "220423_CD4Tcell_extraction_Azimuth.RData"))
```

# 7. sessionInfo

```{r sessionInfo}
sessionInfo()
```
